name: build

on: 
        push:
                branches: [openeuler, opensbi]
        pull_request:
                branches: [openeuler, opensbi]

jobs:
        build_run:
                runs-on: ubuntu-latest
                name: Build and run penglai enclave
                steps:
                  - name: Checkout repository
                    uses: actions/checkout@v2
                  - name: Build and test Penglai monitor (based on OpenSBI).
                    id: build_run
                    uses: Fly0307/action-penglai-opensbi-build-and-test@oe-23
