obj-$(CONFIG_SCSI_FC_HIFC) += hifc.o

hifc-objs += hifc_utils.o
hifc-objs += hifc_hba.o
hifc-objs += hifc_portmng.o

hifc-objs += hifc_module.o
hifc-objs += hifc_chipitf.o
hifc-objs += hifc_io.o
hifc-objs += hifc_queue.o
hifc-objs += hifc_service.o
hifc-objs += hifc_wqe.o
hifc-objs += hifc_cfg.o
hifc-objs += hifc_lld.o

hifc-objs += unf_io.o
hifc-objs += unf_io_abnormal.o
hifc-objs += unf_scsi.o
hifc-objs += unf_init.o
hifc-objs += unf_event.o
hifc-objs += unf_exchg.o
hifc-objs += unf_lport.o
hifc-objs += unf_disc.o
hifc-objs += unf_rport.o
hifc-objs += unf_service.o
hifc-objs += unf_portman.o
hifc-objs += unf_npiv.o
hifc-objs += hifc_sml.o
hifc-objs += hifc_tool.o
hifc-objs += hifc_tool_hw.o
hifc-objs += hifc_dbgtool_knl.o

hifc-objs += hifc_hwif.o
hifc-objs += hifc_eqs.o
hifc-objs += hifc_api_cmd.o
hifc-objs += hifc_mgmt.o
hifc-objs += hifc_wq.o
hifc-objs += hifc_cmdq.o
hifc-objs += hifc_hwdev.o
hifc-objs += hifc_cqm_main.o
hifc-objs += hifc_cqm_object.o
